var model = {
    fields: [{
            name: "email",
            displayName: "Email",
            type: "email",
            typeErrorMessage: "Email, Please enter valid email Id",
            defaultValue: null,
            validate: true,
            display: false,
            required: true,
            requiredErrorMsg: "Email, is required.",
            allowedSpecialChars: "",
            allowedSpecialCharsError: "",
            regExp: "",
            regExpError: "",
            rangeMin: "",
            rangeMinError: "",
            rangeMax: "",
            rangeMaxError: "",
            length: "255",
            lengthErrorMsg: "Email, only 255 alpha numeric characters are allowed.",
            format: "",
            formatErrorMsg: "",
            errorPlaceHolder: ""
        },
        {
            name: "pswd",
            displayName: "Password",
            type: "password",
            typeErrorMessage: "Password, Please enter valid phone",
            defaultValue: null,
            validate: true,
            display: false,
            required: false,
            requiredErrorMsg: "Password, is required.",
            allowedSpecialChars: "",
            allowedSpecialCharsError: "",
            regExp: "",
            regExpError: "",
            rangeMin: "",
            rangeMinError: "",
            rangeMax: "",
            rangeMaxError: "",
            length: "20",
            lengthErrorMsg: "Password, only 12 alpha numeric characters are allowed.",
            format: "",
            formatErrorMsg: "",
            errorPlaceHolder: ""
        },

    ]
};